[package]
name = "random-passwords"
version = "0.1.0"
edition = "2024"
license = "GPL-3"
description = "Simple password generator"

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/random-passwords", dest = "/usr/bin/random-passwords", mode = "0755" },
    { source = "assets/random-passwords.desktop", dest = "/usr/share/applications/random-passwords.desktop", mode = "0644" },
    { source = "assets/icon-original.png", dest = "/usr/share/icons/hicolor/128x128/apps/random-passwords.png", mode = "0644" },
]

[package.metadata.generate-rpm.requires]
# Core C library
glibc = ">= 2.17"

[package.metadata.deb]
assets = [
    { source = "target/release/random-passwords", dest = "/usr/bin/random-passwords", mode = "0755" },
    { source = "assets/random-passwords.desktop", dest = "/usr/share/applications/random-passwords.desktop", mode = "0644" },
    { source = "assets/icon-original.png", dest = "/usr/share/icons/hicolor/128x128/apps/random-passwords.png", mode = "0644" },
]
depends = "libc6, libfontconfig1, libxkbcommon0"

[dependencies]
arboard = "3.6.1"
random_str = "1.1.0"
slint = "1.12.1"

[build-dependencies]
slint-build = "1.12.1"
