import { Button, VerticalBox, CheckBox, GroupBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    in-out property <bool> is_first_checked: false;
    in-out property <bool> is_second_checked: false;
    callback request-increase-value();
    callback request-verify-values();

    VerticalBox {
        VerticalBox {
            CheckBox {
                text: "First";
                checked <=> root.is_first_checked;
            }
            CheckBox {
                text: "Second";
                checked <=> root.is_second_checked;
            }
            Button {
                text: "Verify";
                clicked => {
                    root.request-verify-values();
                }
            }
        }
    }
}
