import { Button, VerticalBox, CheckBox, GroupBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    min-width: 300px;
    min-height: 280px;
    in-out property <bool> uppercase: false;
    in-out property <bool> lowercase: false;
    in-out property <bool> numbers: false;
    in-out property <bool> symbols: false;
    callback request-generate-password();

    GroupBox {
        VerticalBox {
            CheckBox {
                text: "Uppercase";
                checked <=> root.uppercase;
            }
            CheckBox {
                text: "Lowercase";
                checked <=> root.lowercase;
            }
            CheckBox {
                text: "Numbers";
                checked <=> root.numbers;
            }
            CheckBox {
                text: "Symbols";
                checked <=> root.symbols;
            }
            Button {
                text: "Generate";
                clicked => {
                    root.request-generate-password();
                }
            }
        }
    }
}
